'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEBiomassEmitterPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass emitter time series builder.
        '''</summary>
        Friend ReadOnly Property CAPTION_BUILDER() As String
            Get
                Return ResourceManager.GetString("CAPTION_BUILDER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass emitter.
        '''</summary>
        Friend ReadOnly Property CAPTION_EMITTER() As String
            Get
                Return ResourceManager.GetString("CAPTION_EMITTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You do not have any MPAs to apply emission rules to.
        '''</summary>
        Friend ReadOnly Property CHECK_MPAS_MISSING() As String
            Get
                Return ResourceManager.GetString("CHECK_MPAS_MISSING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All emission rules are disabled.
        '''</summary>
        Friend ReadOnly Property CHECK_RULES_DISABLED() As String
            Get
                Return ResourceManager.GetString("CHECK_RULES_DISABLED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have {0} emission rule(s) enabled.
        '''</summary>
        Friend ReadOnly Property CHECK_RULES_ENABLED() As String
            Get
                Return ResourceManager.GetString("CHECK_RULES_ENABLED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have not loaded any emission time series.
        '''</summary>
        Friend ReadOnly Property CHECK_TIMESERIES_MISSING() As String
            Get
                Return ResourceManager.GetString("CHECK_TIMESERIES_MISSING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All emission time series overlap with the Ecospace run period.
        '''</summary>
        Friend ReadOnly Property CHECK_TIMESERIES_OK() As String
            Get
                Return ResourceManager.GetString("CHECK_TIMESERIES_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to One or more emission time series do not overlap with the Ecospace run period.
        '''</summary>
        Friend ReadOnly Property CHECK_TIMESERIES_OUTOFRANGE() As String
            Get
                Return ResourceManager.GetString("CHECK_TIMESERIES_OUTOFRANGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drop region average .csv files here.
        '''</summary>
        Friend ReadOnly Property DROPLABEL_ABSOLUTE() As String
            Get
                Return ResourceManager.GetString("DROPLABEL_ABSOLUTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drop region average .csv files here
        '''(both before and after protection measures).
        '''</summary>
        Friend ReadOnly Property DROPLABEL_RELATIVE() As String
            Get
                Return ResourceManager.GetString("DROPLABEL_RELATIVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EII_transparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EII_transparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ICM_logo_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICM_logo_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Groups expected on first line.
        '''</summary>
        Friend ReadOnly Property PARSE_ERROR_DETAIL_GROUPROW() As String
            Get
                Return ResourceManager.GetString("PARSE_ERROR_DETAIL_GROUPROW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line {0} does not contain enough items.
        '''</summary>
        Friend ReadOnly Property PARSE_ERROR_DETAIL_MISSING() As String
            Get
                Return ResourceManager.GetString("PARSE_ERROR_DETAIL_MISSING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to read the date in line {0}.
        '''</summary>
        Friend ReadOnly Property PARSE_ERROR_DETAIL_PARSEDATE() As String
            Get
                Return ResourceManager.GetString("PARSE_ERROR_DETAIL_PARSEDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to read values in line {0}.
        '''</summary>
        Friend ReadOnly Property PARSE_ERROR_DETAIL_PARSELINE() As String
            Get
                Return ResourceManager.GetString("PARSE_ERROR_DETAIL_PARSELINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Regions expected on second line..
        '''</summary>
        Friend ReadOnly Property PARSE_ERROR_DETAIL_REGIONROW() As String
            Get
                Return ResourceManager.GetString("PARSE_ERROR_DETAIL_REGIONROW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error reading biomass emitter CSV file. {0}.
        '''</summary>
        Friend ReadOnly Property PARSE_ERROR_GENERIC() As String
            Get
                Return ResourceManager.GetString("PARSE_ERROR_GENERIC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select biomass emitter rule file to load.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECTRULEFILE() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECTRULEFILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select biomass emitter trend file to load.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECTTRENDFILE() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECTTRENDFILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pure_magic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pure_magic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Safenet_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Safenet_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} biomass(es) emitted at time step {1}, {2}.
        '''</summary>
        Friend ReadOnly Property STATUS_EMITTED() As String
            Get
                Return ResourceManager.GetString("STATUS_EMITTED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass emitter time series failed to save to {0}. {1}.
        '''</summary>
        Friend ReadOnly Property STATUS_UTILITY_SAVE_ERROR() As String
            Get
                Return ResourceManager.GetString("STATUS_UTILITY_SAVE_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biomass emitter time series saved to {0}.
        '''</summary>
        Friend ReadOnly Property STATUS_UTILITY_SAVE_OK() As String
            Get
                Return ResourceManager.GetString("STATUS_UTILITY_SAVE_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version 0.5, 29 September 2023.
        '''</summary>
        Friend ReadOnly Property VERSION() As String
            Get
                Return ResourceManager.GetString("VERSION", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
