'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEMSPLink.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing ecologically &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property DRIVER_ECOLOGICAL() As String
            Get
                Return ResourceManager.GetString("DRIVER_ECOLOGICAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing effort &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property DRIVER_EFFORT() As String
            Get
                Return ResourceManager.GetString("DRIVER_EFFORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map of Env. driver &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property DRIVER_ENV_NAME() As String
            Get
                Return ResourceManager.GetString("DRIVER_ENV_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map of Habitat &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property DRIVER_HAB_NAME() As String
            Get
                Return ResourceManager.GetString("DRIVER_HAB_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map of MPA &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property DRIVER_MPA_NAME() As String
            Get
                Return ResourceManager.GetString("DRIVER_MPA_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} (Ecosim: {1}, Ecospace: {2}).
        '''</summary>
        Friend ReadOnly Property GAME_SUMMARY() As String
            Get
                Return ResourceManager.GetString("GAME_SUMMARY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sim scenario &apos;{0}&apos; missing.
        '''</summary>
        Friend ReadOnly Property LABEL_ERROR_ECOSIM() As String
            Get
                Return ResourceManager.GetString("LABEL_ERROR_ECOSIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Space scenario &apos;{0}&apos; missing.
        '''</summary>
        Friend ReadOnly Property LABEL_ERROR_ECOSPACE() As String
            Get
                Return ResourceManager.GetString("LABEL_ERROR_ECOSPACE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {1}: {0}, {2}/{3}.
        '''</summary>
        Friend ReadOnly Property OUTPUT_SUMMARY() As String
            Get
                Return ResourceManager.GetString("OUTPUT_SUMMARY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proportion fished.
        '''</summary>
        Friend ReadOnly Property UNITS_EFFORT() As String
            Get
                Return ResourceManager.GetString("UNITS_EFFORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ratio.
        '''</summary>
        Friend ReadOnly Property UNITS_RATIO() As String
            Get
                Return ResourceManager.GetString("UNITS_RATIO", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
