'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEImportExportLayerDefinitionsPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (present).
        '''</summary>
        Friend ReadOnly Property GENERIC_VALUE_PRESENT() As String
            Get
                Return ResourceManager.GetString("GENERIC_VALUE_PRESENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Export Layer Styles....
        '''</summary>
        Friend ReadOnly Property MENU_ITEM_EXPORT() As String
            Get
                Return ResourceManager.GetString("MENU_ITEM_EXPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Import Layer Styles....
        '''</summary>
        Friend ReadOnly Property MENU_ITEM_IMPORT() As String
            Get
                Return ResourceManager.GetString("MENU_ITEM_IMPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select file to load layer styles from.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECTFILE_LOAD() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECTFILE_LOAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select file to save layer styles to.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECTFILE_SAVE() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECTFILE_SAVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property safenet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("safenet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property safenet_full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("safenet_full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property safenet1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("safenet1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export layer styles of all existing Ecospace layers for import elsewhere.
        '''</summary>
        Friend ReadOnly Property TOOLTIP_EXPORT() As String
            Get
                Return ResourceManager.GetString("TOOLTIP_EXPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import Ecospace layer styles, and optionally create missing layers.
        '''</summary>
        Friend ReadOnly Property TOOLTIP_IMPORT() As String
            Get
                Return ResourceManager.GetString("TOOLTIP_IMPORT", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
