'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEMSPPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property block() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("block", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property change() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("change", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game name is not unique!.
        '''</summary>
        Friend ReadOnly Property CHECK_GAME_FAILED() As String
            Get
                Return ResourceManager.GetString("CHECK_GAME_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game name unique.
        '''</summary>
        Friend ReadOnly Property CHECK_GAME_OK() As String
            Get
                Return ResourceManager.GetString("CHECK_GAME_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Ecosim forcing patterns!.
        '''</summary>
        Friend ReadOnly Property CHECK_SIM_FF_FAILED() As String
            Get
                Return ResourceManager.GetString("CHECK_SIM_FF_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Ecosim forcing patterns.
        '''</summary>
        Friend ReadOnly Property CHECK_SIM_FF_OK() As String
            Get
                Return ResourceManager.GetString("CHECK_SIM_FF_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Ecosim fishing patterns!.
        '''</summary>
        Friend ReadOnly Property CHECK_SIM_FISH_FAILED() As String
            Get
                Return ResourceManager.GetString("CHECK_SIM_FISH_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Ecosim fishing patterns.
        '''</summary>
        Friend ReadOnly Property CHECK_SIM_FISH_OK() As String
            Get
                Return ResourceManager.GetString("CHECK_SIM_FISH_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Ecosim time series!.
        '''</summary>
        Friend ReadOnly Property CHECK_SIM_TS_FAILED() As String
            Get
                Return ResourceManager.GetString("CHECK_SIM_TS_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Ecosim time series loaded.
        '''</summary>
        Friend ReadOnly Property CHECK_SIM_TS_OK() As String
            Get
                Return ResourceManager.GetString("CHECK_SIM_TS_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Ecospace time series!.
        '''</summary>
        Friend ReadOnly Property CHECK_SPACE_TS_FAILED() As String
            Get
                Return ResourceManager.GetString("CHECK_SPACE_TS_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Ecospace time series loaded.
        '''</summary>
        Friend ReadOnly Property CHECK_SPACE_TS_OK() As String
            Get
                Return ResourceManager.GetString("CHECK_SPACE_TS_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing ecological.
        '''</summary>
        Friend ReadOnly Property CHOICE_FISHING_ECO() As String
            Get
                Return ResourceManager.GetString("CHOICE_FISHING_ECO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing effort multiplier.
        '''</summary>
        Friend ReadOnly Property CHOICE_FISHING_EFFORT() As String
            Get
                Return ResourceManager.GetString("CHOICE_FISHING_EFFORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Environmental grid.
        '''</summary>
        Friend ReadOnly Property CHOICE_GRID() As String
            Get
                Return ResourceManager.GetString("CHOICE_GRID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CopyHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CopyHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defaults() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defaults", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EcoScope_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EcoScope_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EII() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EII", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map files|*.asc;*.tif;*.tiff.
        '''</summary>
        Friend ReadOnly Property FILEFILTER_TESTSET_MAP() As String
            Get
                Return ResourceManager.GetString("FILEFILTER_TESTSET_MAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Denominator (weight).
        '''</summary>
        Friend ReadOnly Property HEADER_DENOMINATOR() As String
            Get
                Return ResourceManager.GetString("HEADER_DENOMINATOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EwE driver.
        '''</summary>
        Friend ReadOnly Property HEADER_DRIVER() As String
            Get
                Return ResourceManager.GetString("HEADER_DRIVER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numerator (weight).
        '''</summary>
        Friend ReadOnly Property HEADER_NUMERATOR() As String
            Get
                Return ResourceManager.GetString("HEADER_NUMERATOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MSP pressure.
        '''</summary>
        Friend ReadOnly Property HEADER_PRESSURE() As String
            Get
                Return ResourceManager.GetString("HEADER_PRESSURE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raw data.
        '''</summary>
        Friend ReadOnly Property HEADER_RAW() As String
            Get
                Return ResourceManager.GetString("HEADER_RAW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test data.
        '''</summary>
        Friend ReadOnly Property HEADER_TESTDATA() As String
            Get
                Return ResourceManager.GetString("HEADER_TESTDATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value.
        '''</summary>
        Friend ReadOnly Property HEADER_VALUE() As String
            Get
                Return ResourceManager.GetString("HEADER_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_json() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_json", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MSP_Challenge_Icon_037c7c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MSP_Challenge_Icon_037c7c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MSP tools.
        '''</summary>
        Friend ReadOnly Property NODE_CONFIG() As String
            Get
                Return ResourceManager.GetString("NODE_CONFIG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete multiple items? This cannot be undone.
        '''</summary>
        Friend ReadOnly Property PROMPT_DELETE_MULTIPLE() As String
            Get
                Return ResourceManager.GetString("PROMPT_DELETE_MULTIPLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete {0} &quot;{1}&quot;? This cannot be undone.
        '''</summary>
        Friend ReadOnly Property PROMPT_DELETE_SINGLE() As String
            Get
                Return ResourceManager.GetString("PROMPT_DELETE_SINGLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select test map for {0}.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECT_MAP() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECT_MAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rijkswaterstaat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rijkswaterstaat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scriban_black_border() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scriban_black_border", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MSP game configuration failed to save to {0}.
        '''</summary>
        Friend ReadOnly Property STATUS_GAME_EXPORT_FAILED() As String
            Get
                Return ResourceManager.GetString("STATUS_GAME_EXPORT_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MSP game configuration saved to {0}.
        '''</summary>
        Friend ReadOnly Property STATUS_GAME_EXPORT_SUCCESS() As String
            Get
                Return ResourceManager.GetString("STATUS_GAME_EXPORT_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressure &apos;{0}&apos; rejected map &apos;{1}&apos;.
        '''</summary>
        Friend ReadOnly Property STATUS_TESTDATA_MAP_REJECTED() As String
            Get
                Return ResourceManager.GetString("STATUS_TESTDATA_MAP_REJECTED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Testset &apos;{0}&apos; did not load correctly.
        '''</summary>
        Friend ReadOnly Property STATUS_TESTSET_LOAD_FAILED() As String
            Get
                Return ResourceManager.GetString("STATUS_TESTSET_LOAD_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Testset &apos;{0}&apos; loaded correctly.
        '''</summary>
        Friend ReadOnly Property STATUS_TESTSET_LOAD_SUCCESS() As String
            Get
                Return ResourceManager.GetString("STATUS_TESTSET_LOAD_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game.
        '''</summary>
        Friend ReadOnly Property TYPE_GAME() As String
            Get
                Return ResourceManager.GetString("TYPE_GAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Outcome.
        '''</summary>
        Friend ReadOnly Property TYPE_OUTCOME() As String
            Get
                Return ResourceManager.GetString("TYPE_OUTCOME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressure.
        '''</summary>
        Friend ReadOnly Property TYPE_PRESSURE() As String
            Get
                Return ResourceManager.GetString("TYPE_PRESSURE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MSP tools for EwE desktop v 2.1 beta - 25 July 2024.
        '''</summary>
        Friend ReadOnly Property VERSION() As String
            Get
                Return ResourceManager.GetString("VERSION", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
