'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEMPADynamicsPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPA dynamics.
        '''</summary>
        Friend ReadOnly Property DISPLAYNAME() As String
            Get
                Return ResourceManager.GetString("DISPLAYNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property enforced() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enforced", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (initial).
        '''</summary>
        Friend ReadOnly Property GENERIC_VALUE_INITIAL() As String
            Get
                Return ResourceManager.GetString("GENERIC_VALUE_INITIAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property none() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("none", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} failed to save MPA statistics to {1}. {2}.
        '''</summary>
        Friend ReadOnly Property NOTIFICATION_AUTOSAVE_FAILED() As String
            Get
                Return ResourceManager.GetString("NOTIFICATION_AUTOSAVE_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} save MPA statistics to {1}.
        '''</summary>
        Friend ReadOnly Property NOTIFICATION_AUTOSAVE_SUCCESS() As String
            Get
                Return ResourceManager.GetString("NOTIFICATION_AUTOSAVE_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select MPA dynamics file to load.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECT_FILE_LOAD() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECT_FILE_LOAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select where to save the MPA dynamics file.
        '''</summary>
        Friend ReadOnly Property PROMPT_SELECT_FILE_SAVE() As String
            Get
                Return ResourceManager.GetString("PROMPT_SELECT_FILE_SAVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPA &apos;{0}&apos; not found in Ecospace.
        '''</summary>
        Friend ReadOnly Property STATUS_CONFIG_LOAD_ERROR_MPA_UNKNOWN() As String
            Get
                Return ResourceManager.GetString("STATUS_CONFIG_LOAD_ERROR_MPA_UNKNOWN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPA Dynamics CSV file &apos;{0}&apos; failed to load. {1}.
        '''</summary>
        Friend ReadOnly Property STATUS_CONFIG_LOAD_FAILED() As String
            Get
                Return ResourceManager.GetString("STATUS_CONFIG_LOAD_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPA Dynamics CSV file &apos;{0}&apos; loaded.
        '''</summary>
        Friend ReadOnly Property STATUS_CONFIG_LOAD_SUCCESS() As String
            Get
                Return ResourceManager.GetString("STATUS_CONFIG_LOAD_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPA Dynamics CSV file &apos;{0}&apos; failed to save. {1}.
        '''</summary>
        Friend ReadOnly Property STATUS_CONFIG_SAVE_FAILED() As String
            Get
                Return ResourceManager.GetString("STATUS_CONFIG_SAVE_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPA Dynamics CSV file saved to &apos;{0}&apos;.
        '''</summary>
        Friend ReadOnly Property STATUS_CONFIG_SAVE_SUCCESS() As String
            Get
                Return ResourceManager.GetString("STATUS_CONFIG_SAVE_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPA &apos;{1}&apos; changed at {0}. Temporal closure: {2}. Fleet closure: {3}.
        '''</summary>
        Friend ReadOnly Property STATUS_MPA_CHANGED() As String
            Get
                Return ResourceManager.GetString("STATUS_MPA_CHANGED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to all fleets.
        '''</summary>
        Friend ReadOnly Property VALUE_ALL_FLEETS() As String
            Get
                Return ResourceManager.GetString("VALUE_ALL_FLEETS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to all year.
        '''</summary>
        Friend ReadOnly Property VALUE_ALL_YEAR() As String
            Get
                Return ResourceManager.GetString("VALUE_ALL_YEAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to never.
        '''</summary>
        Friend ReadOnly Property VALUE_NEVER() As String
            Get
                Return ResourceManager.GetString("VALUE_NEVER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to none.
        '''</summary>
        Friend ReadOnly Property VALUE_NONE() As String
            Get
                Return ResourceManager.GetString("VALUE_NONE", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
