'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEStepwiseFittingPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An engine that provides a systematic exploration of time series fitting options.
        '''</summary>
        Friend ReadOnly Property DESCRIPTION() As String
            Get
                Return ResourceManager.GetString("DESCRIPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ecosim.
        '''</summary>
        Friend ReadOnly Property DETAIL_ECOSIM() As String
            Get
                Return ResourceManager.GetString("DETAIL_ECOSIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aggregated iteration results.
        '''</summary>
        Friend ReadOnly Property DETAIL_ITERATION_AGGREGATED() As String
            Get
                Return ResourceManager.GetString("DETAIL_ITERATION_AGGREGATED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iteration configuration.
        '''</summary>
        Friend ReadOnly Property DETAIL_ITERATION_CONFIG() As String
            Get
                Return ResourceManager.GetString("DETAIL_ITERATION_CONFIG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Summary.
        '''</summary>
        Friend ReadOnly Property DETAIL_SUMMARY() As String
            Get
                Return ResourceManager.GetString("DETAIL_SUMMARY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stepwise fitting.
        '''</summary>
        Friend ReadOnly Property DISPLAYNAME() As String
            Get
                Return ResourceManager.GetString("DISPLAYNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot access directory {0}..
        '''</summary>
        Friend ReadOnly Property FAILURE_DIRECTORY() As String
            Get
                Return ResourceManager.GetString("FAILURE_DIRECTORY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AIC.
        '''</summary>
        Friend ReadOnly Property HEADER_AIC() As String
            Get
                Return ResourceManager.GetString("HEADER_AIC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AICc.
        '''</summary>
        Friend ReadOnly Property HEADER_AICc() As String
            Get
                Return ResourceManager.GetString("HEADER_AICc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completed.
        '''</summary>
        Friend ReadOnly Property HEADER_COMPLETED() As String
            Get
                Return ResourceManager.GetString("HEADER_COMPLETED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elapsed.
        '''</summary>
        Friend ReadOnly Property HEADER_ELAPSED() As String
            Get
                Return ResourceManager.GetString("HEADER_ELAPSED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to K.
        '''</summary>
        Friend ReadOnly Property HEADER_K() As String
            Get
                Return ResourceManager.GetString("HEADER_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to # spline.
        '''</summary>
        Friend ReadOnly Property HEADER_NUMSPLINE() As String
            Get
                Return ResourceManager.GetString("HEADER_NUMSPLINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to # Vs.
        '''</summary>
        Friend ReadOnly Property HEADER_NUMVULS() As String
            Get
                Return ResourceManager.GetString("HEADER_NUMVULS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SS.
        '''</summary>
        Friend ReadOnly Property HEADER_SS() As String
            Get
                Return ResourceManager.GetString("HEADER_SS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State.
        '''</summary>
        Friend ReadOnly Property HEADER_STATE() As String
            Get
                Return ResourceManager.GetString("HEADER_STATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} and {1}pp.
        '''</summary>
        Friend ReadOnly Property NAME_BASE_AND_SPLINE() As String
            Get
                Return ResourceManager.GetString("NAME_BASE_AND_SPLINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} and {1}v.
        '''</summary>
        Friend ReadOnly Property NAME_BASE_AND_V() As String
            Get
                Return ResourceManager.GetString("NAME_BASE_AND_V", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} and {1}v and {2}pp.
        '''</summary>
        Friend ReadOnly Property NAME_BASE_AND_V_AND_SPLINE() As String
            Get
                Return ResourceManager.GetString("NAME_BASE_AND_V_AND_SPLINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baseline.
        '''</summary>
        Friend ReadOnly Property NAME_BASELINE() As String
            Get
                Return ResourceManager.GetString("NAME_BASELINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fishing.
        '''</summary>
        Friend ReadOnly Property NAME_FISHING() As String
            Get
                Return ResourceManager.GetString("NAME_FISHING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} with time series.
        '''</summary>
        Friend ReadOnly Property NAME_WITH_TS_ONLY() As String
            Get
                Return ResourceManager.GetString("NAME_WITH_TS_ONLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enabled {0} reference time series, {1} driver time series (out of {2}).
        '''</summary>
        Friend ReadOnly Property REPORT_ENABLED_TIMESERIES() As String
            Get
                Return ResourceManager.GetString("REPORT_ENABLED_TIMESERIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to error.
        '''</summary>
        Friend ReadOnly Property REPORT_ERROR() As String
            Get
                Return ResourceManager.GetString("REPORT_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No anomaly shape defined.
        '''</summary>
        Friend ReadOnly Property REPORT_ERROR_NO_SPLINE() As String
            Get
                Return ResourceManager.GetString("REPORT_ERROR_NO_SPLINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} ({1}).
        '''</summary>
        Friend ReadOnly Property REPORT_FORMAT() As String
            Get
                Return ResourceManager.GetString("REPORT_FORMAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} ({1}) - {2}.
        '''</summary>
        Friend ReadOnly Property REPORT_FORMAT_DETAIL() As String
            Get
                Return ResourceManager.GetString("REPORT_FORMAT_DETAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset fishing effort.
        '''</summary>
        Friend ReadOnly Property REPORT_RESET_EFFORT() As String
            Get
                Return ResourceManager.GetString("REPORT_RESET_EFFORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset anomaly shape {0}.
        '''</summary>
        Friend ReadOnly Property REPORT_RESET_SPLINE() As String
            Get
                Return ResourceManager.GetString("REPORT_RESET_SPLINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset Vs.
        '''</summary>
        Friend ReadOnly Property REPORT_RESET_V() As String
            Get
                Return ResourceManager.GetString("REPORT_RESET_V", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run Ecosim.
        '''</summary>
        Friend ReadOnly Property REPORT_RUN_ECOSIM() As String
            Get
                Return ResourceManager.GetString("REPORT_RUN_ECOSIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run pred sens {0}v.
        '''</summary>
        Friend ReadOnly Property REPORT_RUN_SENSV_PRED() As String
            Get
                Return ResourceManager.GetString("REPORT_RUN_SENSV_PRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run pred/prey sens {0}v.
        '''</summary>
        Friend ReadOnly Property REPORT_RUN_SENSV_PREDPREY() As String
            Get
                Return ResourceManager.GetString("REPORT_RUN_SENSV_PREDPREY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run {0}pp.
        '''</summary>
        Friend ReadOnly Property REPORT_RUN_SPLINE() As String
            Get
                Return ResourceManager.GetString("REPORT_RUN_SPLINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run {0}v.
        '''</summary>
        Friend ReadOnly Property REPORT_RUN_V() As String
            Get
                Return ResourceManager.GetString("REPORT_RUN_V", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run {0}v {1}pp.
        '''</summary>
        Friend ReadOnly Property REPORT_RUN_V_SPLINE() As String
            Get
                Return ResourceManager.GetString("REPORT_RUN_V_SPLINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to not needed.
        '''</summary>
        Friend ReadOnly Property REPORT_SKIPPED() As String
            Get
                Return ResourceManager.GetString("REPORT_SKIPPED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to success.
        '''</summary>
        Friend ReadOnly Property REPORT_SUCCESS() As String
            Get
                Return ResourceManager.GetString("REPORT_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set {0}v for groups with time series.
        '''</summary>
        Friend ReadOnly Property REPORT_V_FOR_GROUPS_WITH_TIMESERIES() As String
            Get
                Return ResourceManager.GetString("REPORT_V_FOR_GROUPS_WITH_TIMESERIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend ReadOnly Property STATE_ITERATION_ERROR() As String
            Get
                Return ResourceManager.GetString("STATE_ITERATION_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (initializing).
        '''</summary>
        Friend ReadOnly Property STATE_ITERATION_INITIALIZING() As String
            Get
                Return ResourceManager.GetString("STATE_ITERATION_INITIALIZING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property STATE_ITERATION_OK() As String
            Get
                Return ResourceManager.GetString("STATE_ITERATION_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (pending).
        '''</summary>
        Friend ReadOnly Property STATE_ITERATION_PENDING() As String
            Get
                Return ResourceManager.GetString("STATE_ITERATION_PENDING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (running).
        '''</summary>
        Friend ReadOnly Property STATE_ITERATION_RUNNING() As String
            Get
                Return ResourceManager.GetString("STATE_ITERATION_RUNNING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (stopping).
        '''</summary>
        Friend ReadOnly Property STATE_ITERATION_STOPPING() As String
            Get
                Return ResourceManager.GetString("STATE_ITERATION_STOPPING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} initializing.
        '''</summary>
        Friend ReadOnly Property STATUS_INITIALIZING() As String
            Get
                Return ResourceManager.GetString("STATUS_INITIALIZING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} in progress.
        '''</summary>
        Friend ReadOnly Property STATUS_RUNNING() As String
            Get
                Return ResourceManager.GetString("STATUS_RUNNING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} results could not be saved. {1}.
        '''</summary>
        Friend ReadOnly Property STATUS_SAVE_DETAIL_FAILED() As String
            Get
                Return ResourceManager.GetString("STATUS_SAVE_DETAIL_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} results saved to {1}.
        '''</summary>
        Friend ReadOnly Property STATUS_SAVE_DETAIL_SUCCESS() As String
            Get
                Return ResourceManager.GetString("STATUS_SAVE_DETAIL_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} results could not be saved.
        '''</summary>
        Friend ReadOnly Property STATUS_SAVE_FAILED() As String
            Get
                Return ResourceManager.GetString("STATUS_SAVE_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} results saved successfully.
        '''</summary>
        Friend ReadOnly Property STATUS_SAVE_SUCCESS() As String
            Get
                Return ResourceManager.GetString("STATUS_SAVE_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} saving CSV files....
        '''</summary>
        Friend ReadOnly Property STATUS_SAVING() As String
            Get
                Return ResourceManager.GetString("STATUS_SAVING", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
