'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEEcoEngineersPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CIB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CIB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An engine that calculates a habitat complexity map from various ecosystem engineer biomasses..
        '''</summary>
        Friend ReadOnly Property DRIVER_DESCRIPTION() As String
            Get
                Return ResourceManager.GetString("DRIVER_DESCRIPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EcoEngineer driver.
        '''</summary>
        Friend ReadOnly Property DRIVER_NAME() As String
            Get
                Return ResourceManager.GetString("DRIVER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EII() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EII", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This name is reserved. Please select another name..
        '''</summary>
        Friend ReadOnly Property ERROR_DEFAULT_EXISTS() As String
            Get
                Return ResourceManager.GetString("ERROR_DEFAULT_EXISTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (unnamed function).
        '''</summary>
        Friend ReadOnly Property FUNCTION_NONAME() As String
            Get
                Return ResourceManager.GetString("FUNCTION_NONAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IRD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IRD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ma_Re() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ma_Re", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} (high shore).
        '''</summary>
        Friend ReadOnly Property MASK_HIGHSHORE() As String
            Get
                Return ResourceManager.GetString("MASK_HIGHSHORE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} (low shore).
        '''</summary>
        Friend ReadOnly Property MASK_LOWSHORE() As String
            Get
                Return ResourceManager.GetString("MASK_LOWSHORE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mellon_foundation_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mellon_foundation_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plymouth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plymouth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EcoEngineer complexity raster.
        '''</summary>
        Friend ReadOnly Property RASTER_NAME() As String
            Get
                Return ResourceManager.GetString("RASTER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sarchi_logo_small_colour_web() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sarchi_logo_small_colour_web", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Southampton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Southampton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stellenbosch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stellenbosch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property the_marine_lab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("the_marine_lab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UCT_biological_sciences() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UCT_biological_sciences", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
