'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EwEShapeFunctionPlugin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plug-in that provides a Sinoid shape function to EwE 6.
        '''</summary>
        Friend ReadOnly Property DESCIRPTION_SINOID() As String
            Get
                Return ResourceManager.GetString("DESCIRPTION_SINOID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plug-in that adds noise to a shape in EwE 6.
        '''</summary>
        Friend ReadOnly Property DESCRIPTION_NOISE() As String
            Get
                Return ResourceManager.GetString("DESCRIPTION_NOISE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Noised up.
        '''</summary>
        Friend ReadOnly Property NAME_NOISE() As String
            Get
                Return ResourceManager.GetString("NAME_NOISE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sinoid.
        '''</summary>
        Friend ReadOnly Property NAME_SINOID() As String
            Get
                Return ResourceManager.GetString("NAME_SINOID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amplitude.
        '''</summary>
        Friend ReadOnly Property PARAM_AMPLITUDE() As String
            Get
                Return ResourceManager.GetString("PARAM_AMPLITUDE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bandwidth.
        '''</summary>
        Friend ReadOnly Property PARAM_BAND() As String
            Get
                Return ResourceManager.GetString("PARAM_BAND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Offset.
        '''</summary>
        Friend ReadOnly Property PARAM_OFFSET() As String
            Get
                Return ResourceManager.GetString("PARAM_OFFSET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repetitions.
        '''</summary>
        Friend ReadOnly Property PARAM_REPETITION() As String
            Get
                Return ResourceManager.GetString("PARAM_REPETITION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Y zero.
        '''</summary>
        Friend ReadOnly Property PARAM_YZERO() As String
            Get
                Return ResourceManager.GetString("PARAM_YZERO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to deg..
        '''</summary>
        Friend ReadOnly Property UNIT_OFFSET() As String
            Get
                Return ResourceManager.GetString("UNIT_OFFSET", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
